<!-- Content Section -->
<section>
    <div class="container text-center">
        <div class="row">
            <div class="col-lg-12">
                <h1 class="section-heading">Welcome To Project Overground</h1>
                <p class="section-paragraph">
                    Project Overground is an open source PHP MVC Framework currently in BETA.
                </p>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="col-lg-12" align="center">
            <a href="https://github.com/FredCWeb/ProjectOverground">
                <i class="glyphicon glyphicon-file" style="font-size: 40px; color: #3c763d;"></i><br>
                <strong>Download Now @ https://github.com/FredCWeb/ProjectOverground</strong>
            </a>
        </div>
    </div>
</section>
