<!-- Content Section -->
<section>
    <div class="container text-center">
        <div class="row">
            <div class="col-lg-12">
                <h1 class="section-heading">Welcome To Project Overground</h1>
                <p class="section-paragraph">
                    Project Overground is an open source PHP MVC Framework currently in production. We are hoping to release it to the public by January 2017.
                </p>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="col-lg-12">
            <i class="glyphicon glyphicon-file" style="font-size: 40px; color: #3c763d;"></i>
        </div>
    </div>
</section>
